v5.4: config system, silk pop-up flag, fixes

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -54,13 +54,12 @@ print_modname() {
   [ $namelen -gt $authlen ] && len=$namelen || len=$authlen
   len=$((len + 2))
   pounds=$(printf "%${len}s" | tr ' ' '*')
-  ui_print "$pounds"
-  ui_print " $MODNAME "
-  ui_print " by $MODAUTH "
-  ui_print "$pounds"
-  ui_print "*******************"
-  ui_print " Powered by Magisk "
-  ui_print "*******************"
+  ui_print "* "
+  ui_print "* $MODNAME "
+  ui_print "* by $MODAUTH "
+  ui_print "* "
+  ui_print "* Powered by Magisk "
+  ui_print "* "
 }
 
 # Override abort as old scripts have some issues
@@ -93,7 +92,7 @@ $BOOTMODE && boot_actions || recovery_actions
 
 # Extract prop file
 unzip -o "$ZIPFILE" module.prop -d $TMPDIR >&2
-[ ! -f $TMPDIR/module.prop ] && abort "! Unable to extract zip file!"
+[ ! -f $TMPDIR/module.prop ] && abort "* Unable to extract zip file!"
 
 $BOOTMODE && MODDIRNAME=modules_update || MODDIRNAME=modules
 MODULEROOT=$NVBASE/$MODDIRNAME
@@ -138,7 +137,7 @@ if is_legacy_script; then
   # service scripts
   $LATESTARTSERVICE && cp -af $TMPDIR/service.sh $MODPATH/service.sh
 
-  ui_print "- Setting permissions"
+  ui_print "* Setting permissions"
   set_permissions
 else
   print_modname
@@ -146,7 +145,7 @@ else
   unzip -o "$ZIPFILE" customize.sh -d $MODPATH >&2
 
   if ! grep -q '^SKIPUNZIP=1$' $MODPATH/customize.sh 2>/dev/null; then
-    ui_print "- Extracting module files"
+    ui_print "* Extracting module files"
     unzip -o "$ZIPFILE" -x 'META-INF/*' -d $MODPATH >&2
 
     # Default permissions
@@ -159,7 +158,7 @@ fi
 
 # Handle replace folders
 for TARGET in $REPLACE; do
-  ui_print "- Replace target: $TARGET"
+  ui_print "  | Replace target: $TARGET"
   mktouch $MODPATH$TARGET/.replace
 done
 
@@ -171,12 +170,12 @@ fi
 
 # Copy over custom sepolicy rules
 if [ -f $MODPATH/sepolicy.rule -a -e $PERSISTDIR ]; then
-  ui_print "- Installing custom sepolicy patch"
+  ui_print "* Installing custom sepolicy patch"
   # Remove old recovery logs (which may be filling partition) to make room
   rm -f $PERSISTDIR/cache/recovery/*
   PERSISTMOD=$PERSISTDIR/magisk/$MODID
   mkdir -p $PERSISTMOD
-  cp -af $MODPATH/sepolicy.rule $PERSISTMOD/sepolicy.rule || abort "! Insufficient partition size"
+  cp -af $MODPATH/sepolicy.rule $PERSISTMOD/sepolicy.rule || abort "* Insufficient partition size"
 fi
 
 # Remove stuffs that don't belong to modules
@@ -192,5 +191,5 @@ cd /
 $BOOTMODE || recovery_cleanup
 rm -rf $TMPDIR
 
-ui_print "- Done"
+ui_print "  | Done"
 exit 0
